# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
# - hosts: all
#   gather_facts: false
#   tasks:
#     - raw: which python || apt-get update
#     - raw: (which python && which aptitude) || apt-get install -y python python-apt aptitude
# - hosts: web
#   tasks:
#     - name: Upgrade APT
#       apt: upgrade=yes
#     - name: Install ca-certificates
#       apt: name=ca-certificates state=latest
#     - name: Install dumb-init
#       apt: deb=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb
#     - name: Install Apache
#       apt: name=apache2 state=latest

